version: "3.8"
services:
    api:
        build: 
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        environment: 
            DATABASE_URL: "postgres://user:password@postgres:5432/db"
            NODE_ENV: development
            PORT: 3000
            NODE_OPTIONS: --max_old_space_size=8048
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
            POSTGRES_PORT: 5432
        ports:
            - "8090:3000"
        restart: on-failure  

    postgres:
        image: postgres:14-alpine
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        restart: on-failure  


            



